### ISSUE TITLE
implementation需要更新，不是com.gitee.tjbaobao:GoogleBilling

### ISSUE THREAD

**Issue by likky** [TJHello/GoogleBilling#2]
dependencies {
    implementation 'com.gitee.tjbaobao:GoogleBilling:1.2.1-beta05'
}
 sbt.ResolveException: unresolved dependency: com.gitee.tjbaobao#GoogleBilling;*: not found

**Comment by likky** [comment]
哥们，原来是使用这个才行！
implementation 'com.github.TJHello:GoogleBilling:1.2.1-beta06'
请在主页改一下吧

**Comment by TJHello** [comment]
我的锅，后面已经改过来了。
