### ISSUE TITLE
服务器验证和非自动消耗

### ISSUE THREAD

**Issue by SteveYung** [TJHello/GoogleBilling#4]
您好,使用的版本是:2.0.3.10-alpha02
Google提供下列三种方式.
您可以使用以下某种方法确认购买交易：

对于消耗型商品，请使用客户端 API 中的 consumeAsync()。
对于非消耗型商品，请使用客户端 API 中的 acknowledgePurchase()。
还可以使用服务器 API 中新增的 acknowledge() 方法。

如果我使用第三种方式的话我需要怎么做呢？
onRecheck 和 onPurchaseSuccess的方法的返回值都应该设置成false吗?
然后再通过以下链接进行消耗吗?
GET https://www.googleapis.com/androidpublisher/v3/applications/packageName/purchases/products/productId/tokens/token

**Comment by TJHello** [comment]
返回false就是不进行确认购买和消耗。如果有其他途径进行消耗或者确认购买的话，是可以的。但具体后台的api我不是很清楚，需要你去具体了解。
