### ISSUE TITLE
谷歌支付失败

### ISSUE THREAD

**Issue by 13437543491** [TJHello/GoogleBilling#5]
支付的时候返回6，api发生严重错误，这个是怎么回事知道吗？充值小金额是可以的，充值大金额就返回这个错误

**Comment by TJHello** [comment]
目前我没有收到过，小金额能支付大金额不能支付的反馈，请确保谷歌套件是最新的，不然可能存在一些功能兼容问题。还有问题可以加群讨论。

**Comment by gxs-gc** [comment]
有可能是网络的问题
