### ISSUE TITLE
未确认商品购买

### ISSUE THREAD

**Issue by crook3** [TJHello/GoogleBilling#6]
你好，请问一下，如果setIsAutoAcknowledgePurchase设置为false, 并且我们后台也没有去确认，是不是3天内谷歌会自动退款？望回复。

**Comment by TJHello** [comment]
按照谷歌那边的规则，2.0.0版本以上是的，必须要我们确认购买。但值得注意的是，内购商品的消耗商品也包含确认购买的操作。

**Comment by crook3** [comment]
好的，谢谢，已解决。
