### ISSUE TITLE
querySkuDetailsAsync拿不到订阅商品信息，数组空

### ISSUE THREAD

**Issue by wuqifeng** [TJHello/GoogleBilling#9]
发了内部测试已发布，但是分享的链接给测试人员，测试打开显示store搜不到该应用

**Comment by TJHello** [comment]
请参考第五点注意事项：

5. 查询的时候返回的商品列表长度为0。

setSkus的时候将内购sku和订阅sku的参数顺序弄错了，应该是第一个是内购的，第二个参数是订阅的。

或者是商品还没有发布成功，需要等待一段时间(很有可能，新发布的商品是无论怎么查询还是购买，谷歌那边都是没有响应的)

**Comment by TJHello** [comment]
请参考第五点注意事项：

5. 查询的时候返回的商品列表长度为0。

setSkus的时候将内购sku和订阅sku的参数顺序弄错了，应该是第一个是内购的，第二个参数是订阅的。

或者是商品还没有发布成功，需要等待一段时间(很有可能，新发布的商品是无论怎么查询还是购买，谷歌那边都是没有响应的)
